apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-mikrofrontend-eksempel
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-mikrofrontend-eksempel-secrets
  image: {{ image }}
  port: 7150
  liveness:
    path: /tms-mikrofrontend-eksempel/internal/isAlive
    initialDelay: 10
  readiness:
    path: /tms-mikrofrontend-eksempel/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /tms-mikrofrontend-eksempel/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://www.intern.nav.no/tms-mikrofrontend-eksempel"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
